name: "Tests"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: npmlock2nix
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: nix-shell --run "nixpkgs-fmt --check ."
      - name: Try latest stable Nix release
        run:  nix-shell -I nixpkgs=nix -p nix --run ./test.sh
      - name: Try tests with nix 2.3
        run:  nix-shell -I nixpkgs=nix -p nix_2_3 --run ./test.sh
